//
//  AppLovinMAXGodotSignal.h
//  AppLovin-MAX-Godot-Plugin
//
//  Created by Chris Cong on 9/17/23.
//

#import <Foundation/Foundation.h>

#include "core/object/class_db.h"

extern String AppLovinMAXSignalSdkInitialization;

extern String AppLovinMAXSignalBannerOnAdLoaded;
extern String AppLovinMAXSignalBannerOnAdLoadFailed;
extern String AppLovinMAXSignalBannerOnAdClicked;
extern String AppLovinMAXSignalBannerOnAdRevenuePaid;
extern String AppLovinMAXSignalBannerOnAdExpanded;
extern String AppLovinMAXSignalBannerOnAdCollapsed;

extern String AppLovinMAXSignalMRecOnAdLoaded;
extern String AppLovinMAXSignalMRecOnAdLoadFailed;
extern String AppLovinMAXSignalMRecOnAdClicked;
extern String AppLovinMAXSignalMRecOnAdRevenuePaid;
extern String AppLovinMAXSignalMRecOnAdExpanded;
extern String AppLovinMAXSignalMRecOnAdCollapsed;

extern String AppLovinMAXSignalInterstitialOnAdLoaded;
extern String AppLovinMAXSignalInterstitialOnAdLoadFailed;
extern String AppLovinMAXSignalInterstitialOnAdClicked;
extern String AppLovinMAXSignalInterstitialOnAdRevenuePaid;
extern String AppLovinMAXSignalInterstitialOnAdDisplayed;
extern String AppLovinMAXSignalInterstitialOnAdDisplayFailed;
extern String AppLovinMAXSignalInterstitialOnAdHidden;

extern String AppLovinMAXSignalAppOpenOnAdLoaded;
extern String AppLovinMAXSignalAppOpenOnAdLoadFailed;
extern String AppLovinMAXSignalAppOpenOnAdClicked;
extern String AppLovinMAXSignalAppOpenOnAdRevenuePaid;
extern String AppLovinMAXSignalAppOpenOnAdDisplayed;
extern String AppLovinMAXSignalAppOpenOnAdDisplayFailed;
extern String AppLovinMAXSignalAppOpenOnAdHidden;

extern String AppLovinMAXSignalRewardedOnAdLoaded;
extern String AppLovinMAXSignalRewardedOnAdLoadFailed;
extern String AppLovinMAXSignalRewardedOnAdClicked;
extern String AppLovinMAXSignalRewardedOnAdRevenuePaid;
extern String AppLovinMAXSignalRewardedOnAdDisplayed;
extern String AppLovinMAXSignalRewardedOnAdDisplayFailed;
extern String AppLovinMAXSignalRewardedOnAdHidden;
extern String AppLovinMAXSignalRewardedOnAdReceivedReward;
